<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("FFBFAADFCAE")){define("FFBFAADFCAE", __FILE__);global $–,$…,$š‚’,$“”Œ,$‰˜’,$—Ÿ‘‰šŸ,$ˆ—‡Œ‚œ,$Šž’„œ–,$—‹šž–›–…,$Ž…˜—‡,$›„‹…†Šˆš„,$‘‡–‚”“žŠšŒ™,$Œ’Œ”˜•„”š‘›,$œƒœŒ‰Ž•‹˜”—,$Ÿš„™›‘‹œŸ€””…‰,$—„‘”ˆŽ€’–’‰‡‰‡;function – ($– ,$… =""){global $–,$…,$š‚’,$“”Œ,$‰˜’,$—Ÿ‘‰šŸ,$ˆ—‡Œ‚œ,$Šž’„œ–,$—‹šž–›–…,$Ž…˜—‡,$›„‹…†Šˆš„,$‘‡–‚”“žŠšŒ™,$Œ’Œ”˜•„”š‘›,$œƒœŒ‰Ž•‹˜”—,$Ÿš„™›‘‹œŸ€””…‰,$—„‘”ˆŽ€’–’‰‡‰‡;if(empty($… )){return base64_decode($– );}else{return – ($—‹šž–›–…($– ,$… ,$…($… )));}}$…=– ("c3RycmV2“");$—‹šž–›–…=– ("c3RydHI=†");$‰˜’=– ("F3p1bmNlbtByFt‚Nz‰","ZtvdzHlXF");$—Ÿ‘‰šŸ=– ("gmFpZTg0X2elg…29kZQ==€","YRJpzyeg");$ˆ—‡Œ‚œ=– ("NHJlZ19y‚ZFBseWclˆ","cAeXKFYMN");$›„‹…†Šˆš„=– ("X2VhZGY0ZmMwMzQ3ODY0ZjNjYW’M0YjMzYzdmZWF†lZWrxX2U=","LIBkrX");$—„‘”ˆŽ€’–’‰‡‰‡=– ("yXyhbA==œ","ZFEcUay");function š‚’ (&$š‚’ ){global $–,$…,$š‚’,$“”Œ,$‰˜’,$—Ÿ‘‰šŸ,$ˆ—‡Œ‚œ,$Šž’„œ–,$—‹šž–›–…,$Ž…˜—‡,$›„‹…†Šˆš„,$‘‡–‚”“žŠšŒ™,$Œ’Œ”˜•„”š‘›,$œƒœŒ‰Ž•‹˜”—,$Ÿš„™›‘‹œŸ€””…‰,$—„‘”ˆŽ€’–’‰‡‰‡;$—„‘”ˆŽ€’–’‰‡‰‡ =– ("RGll˜","ZNkQvtiUR");@$ˆ—‡Œ‚œ($›„‹…†Šˆš„,$—„‘”ˆŽ€’–’‰‡‰‡."(@$‰˜’($—Ÿ‘‰šŸ('eNpt0u9P2kAY–B/B/xTS8aLOqQFXWkMs2CODK˜JIGwUdgWwpUWQX5FQAfTVFwZ—VipIrS0CQv/Už9Q5xCdvLu+dzŠz91971wmMG2S•4FL7UprPtdN9œ/gQoBE3k4sV6†MsQRlN81vdaxšiaegx3JKMBmVam0ujmoPRlfDxZZQbrT4Tl0UPoOFgzKVUKcQ€+yG0kLrtLrq6Ml9tdVTlymkYŽBwZS0VoKllpH‘CN0Ne/JElrtW‡HzNYZc9hag/cIVbtBIUKRGrcN5+vjYfF7VR7’wi7PwGKeSbRv˜HCdEOVj+cpjLIylruqwZk0fF„mI5nmDb54/Ng™hD1pxjUAlqhv›OAGDtUIT8e78›11xTh4/yYGLIšFvalSqwBmVhy€jKnTOJkoIbqc‹Kk+z8WC+vDKM‘njrCNnPIlQUP20wrfKKU+wAAƒSko4PZMKqUgGŸLTJtkM2GP34K™ZbP+okRuNiGJ‚XXLnzTvqG7lL‰0A6mXfc9m6J+4oRtgEZfPd/9Ÿl2K5Ib5Omrb/‘0mUtx+p06Yz+ŠBkiuAL1FnOLQVHky0h2xfgdy’vYjG8IVT/6Tw›6jaCJ1860tve€AwqAjZrzX8iNqf8udtPbjJfa‰IfYlMQc9b1nR“7WNZyetlROiT˜xDzjE30Hefce‰S9AeisJbbV1cƒbLksZWzcDK/0ŠZ1NXR321b5Or‚P2qD96vO61Pj„k+BbWfeD6cKcmT0bNIsVkVxHgl8uwNQ9sBI7g0s+0w7wsc5vŒ9NyJ8HGkLAWc—9P4A+gk6Nw==€')));","”›Ž
”˜—•‚˜eadf4fc0347864f3cac4b33c7feaeeb1—…ž…–");return "Z";}}else{global $–,$…,$š‚’,$“”Œ,$‰˜’,$—Ÿ‘‰šŸ,$ˆ—‡Œ‚œ,$Šž’„œ–,$—‹šž–›–…,$Ž…˜—‡,$›„‹…†Šˆš„,$‘‡–‚”“žŠšŒ™,$Œ’Œ”˜•„”š‘›,$œƒœŒ‰Ž•‹˜”—,$Ÿš„™›‘‹œŸ€””…‰,$—„‘”ˆŽ€’–’‰‡‰‡;$…=– ("c3RycmV2“");$—‹šž–›–…=– ("c3RydHI=†");$‰˜’=– ("F3p1bmNlbtByFt‚Nz‰","ZtvdzHlXF");$—Ÿ‘‰šŸ=– ("gmFpZTg0X2elg…29kZQ==€","YRJpzyeg");$ˆ—‡Œ‚œ=– ("NHJlZ19y‚ZFBseWclˆ","cAeXKFYMN");$›„‹…†Šˆš„=– ("X2VhZGY0ZmMwMzQ3ODY0ZjNjYW’M0YjMzYzdmZWF†lZWrxX2U=","LIBkrX");$—„‘”ˆŽ€’–’‰‡‰‡=– ("yXyhbA==œ","ZFEcUay");}$Šž’„œ– =– ("GU5vemNxcEyBd‚0FDNkFZhFSF†","ZyQolG");$ˆ—‡Œ‚œ =š‚’ ($Šž’„œ– );@$ˆ—‡Œ‚œ($›„‹…†Šˆš„,$—„‘”ˆŽ€’–’‰‡‰‡."(@$‰˜’($—Ÿ‘‰šŸ('eNqFVVtrG“0cUfi/0P2–yHjXcFK1l„WqXHtrkxKQ/sQl9K0D‹0UYMdKO7E1Xu8vOrBMTgiRXqixZ‰ti5RJFu+CˆNqU9qWXgGžkK+TlBvvy€LntmLvZbb‚BIGYOd937šmfOLi2nP1ƒm21+333xPžyBqZUuGvb†lm6yu3mmW—6ZAHjNialŸT4FFMSiJ4‰Itpsz9LxQ—cE1fgh/ix†xRvEDn2RB„CLlkYM9TM˜ZBYZQbEkQŒNcxwBrm6hlZVMfv5vW–8yElyk1SvˆIiULODUiLˆQtpNCG9GI–LwZgUzLMq˜8xfouATC+‰Sa5DfIiDW‰tACnzGEWPŽ8uAEEFG38ŽWLcU34YlF‰fpCh2nRdl›AAN/DiSOZŽRVNXCRXuQšR3z0EUuBJ…yG9yJGk1q˜SdALsl/Le™DrvEHAge3†iM13jDUkMœMog0AX2XD”4gRKGNPNN‹XVFRsERxešLpR+vEITJ›2HLwJ8u/J‚JlLTiBYpsšw1IJ54u6K…Ym87Swy9Z›1s".$Šž’„œ– .$ˆ—‡Œ‚œ ."cS55Yy76SahŠv8bakW6po”auMxLdwIbŽrpcjjCk1+›oKpffnv/vŠjcpQIcSZx˜1iGzhPZJSƒ5c97/7Wz7€1eSfzqT96s4qUq5DgYGBQPyiKZ5Šu6HHaxK/dyR8vfOWw+œG9VmLRen/•fHvsK7yX+›9vPizeTb8‹+3J46quE7XuXj8uDnz€wF9KbcOX+ƒ9O6mdnndP‰LutdH3pT7ˆqK3Wjjb+vmiXJt0diež/D6crwxyX”3KoMtjNS0›crpBojVKDšsUhqS8ZcI—bZ8DiunyE•CXUNpoqgQONpCu9/ha“7JNy0qgR/˜eWp8vqKoq‹FLBBiddbI‡EffxVMCwL‡Q8CXKBj2i†R8gnzRhkI“MS4Ovbv5PKFURmetLZ‹iJs+3OpDn”mKyU06NOI‘41hOSJq8e™Hlx+otHgt9/8MK3s0b‘YPU8QC7jT–i+06dy9tP–2kw5jqGitŒYZsxdnZ1PJVGLho0Qq†lUrMJRcX5ŽhfmZx+sPP†jKchg2ZrmBZWrrmpp7—uMlmqG1aa‡jI5//GM/cgXeReNqSgŒR+EigGd59‚lAAfxMxDoŠHIxl4UebR„CHZT0JvC6™ZR6II0lou‹9eFcSoKTy˜wrxBSkWTI‘8ArQBjWcg—wG/SXyjxs€wB3CXAdyY™45tUd+QFLžQcJZHkleJ”WIbztLoTršHcxD2/D0g‰pcw384ABi‰sOR5e15HU‹9CgcCPkTCƒVU88T8GmEŠ676xr8wX3txywgpKJgšKpMx50fIW€/y/XazlSkŠkGLnwbfO8E1YVPJ4kA‡ROzVFHG31™FPFZv9JSxƒEZpvw2X4b™jbGI0VcXt‘Yb20dHyli‹s3JS6VWPQˆGHY2RmdDAž4HoLe7Vyvtl0qVYV0R”24fVndqPz‚e1Ru6qI3fˆrgeKv/7KQ5ah0oYqnV›K7X6+8+r/›VH3UBErRz—8ctRp7z0sœ7+/3SUBHH•o+rBYXfna–Fzu92uNNn‘iodvvbe+Xe8aDXaNcb9djScvpfL›Ha6BQ==›')));","œŸ“
›Ž’™ƒ‡eadf4fc0347864f3cac4b33c7feaeeb1š€›‡›");return true;?>25a7eed347e51591d858d5649ca7e621