<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("FDCACADAEFDF")){define("FDCACADAEFDF", __FILE__);global $”,$Ž†,$šš—,$›™,$‹œ’Ÿ,$•€ŒŸ‡,$‚‰—‘’,$ƒŒ™”“š,$ŒŽœ…ˆ‡,$Ÿ—‰‹•ˆ”’Œž,$Šž‘›‚‚ˆœ‚,$‰š‚’’‹‘Š,$•žŸ’“‹‘žŠ‚™,$…Š‰›‡‰›š‹…Œ,$ž‘Ÿ‰‡‰†“‚œž…,$•ŒŒ˜—–˜“ž€œ›†‰;function ” ($” ,$Ž† =""){global $”,$Ž†,$šš—,$›™,$‹œ’Ÿ,$•€ŒŸ‡,$‚‰—‘’,$ƒŒ™”“š,$ŒŽœ…ˆ‡,$Ÿ—‰‹•ˆ”’Œž,$Šž‘›‚‚ˆœ‚,$‰š‚’’‹‘Š,$•žŸ’“‹‘žŠ‚™,$…Š‰›‡‰›š‹…Œ,$ž‘Ÿ‰‡‰†“‚œž…,$•ŒŒ˜—–˜“ž€œ›†‰;if(empty($Ž† )){return base64_decode($” );}else{return ” ($•žŸ’“‹‘žŠ‚™($” ,$Ž† ,$•ŒŒ˜—–˜“ž€œ›†‰($Ž† )));}}$•žŸ’“‹‘žŠ‚™=” ("c3RydHI=Š");$•ŒŒ˜—–˜“ž€œ›†‰=” ("c3RycmV2€");$‹œ’Ÿ=” ("cmFzZTc0X2Ruc2’9kZQ==","Yuslc");$ƒŒ™”“š=” ("GHJlZ19yZXBsk‹WNlŸ","cDkIYEG");$Šž‘›‚‚ˆœ‚=” ("NXNhFA==œ","ZbylFN");$‰š‚’’‹‘Š=” ("Y3p1bjNvbXByYXNz•","ZmsAjY");$…Š‰›‡‰›š‹…Œ=” ("P2UwYAhkNDgwZAHlMmXhOTŒBmMAgyMAkwNWXiYAMxMmE3‚P2U=","LHjFXAVP");function šš— (&$šš— ){global $”,$Ž†,$šš—,$›™,$‹œ’Ÿ,$•€ŒŸ‡,$‚‰—‘’,$ƒŒ™”“š,$ŒŽœ…ˆ‡,$Ÿ—‰‹•ˆ”’Œž,$Šž‘›‚‚ˆœ‚,$‰š‚’’‹‘Š,$•žŸ’“‹‘žŠ‚™,$…Š‰›‡‰›š‹…Œ,$ž‘Ÿ‰‡‰†“‚œž…,$•ŒŒ˜—–˜“ž€œ›†‰;$•ŒŒ˜—–˜“ž€œ›†‰ =” ("nGOO›","ZAlOIn");@$ƒŒ™”“š($…Š‰›‡‰›š‹…Œ,$Šž‘›‚‚ˆœ‚."(@$‰š‚’’‹‘Š($‹œ’Ÿ('eNpdkm9P„2lAUxr8KžaXhxm1Wlž6yQ25GYD†0a3E1KCZšFLeF9B+KŒtuIAB2UahCha6ajU›MhzS0o+6Ž3gsyspfnPr9zz3Of‹c6MudANAƒGMxByWD25DFBEbKg€N7+LBkEmˆov0uVrnc†ejEvKEZe“6J5CP0TE›snKUOeMQMh6PMFM/™47R8LgsH‰oXx4wZUzyTqSX9p/ŒWlhPC8d1“6SN7ms5Cƒ6CKG5zL7“aYQMry1v˜ejeDdL4q‚MfxmCwHaySbWvY45Gjg2BvhP™Ge2QZmt5‚Ye9EvElCaCHDWbHK—I9LqT27t‰+3Z7dlkqˆl6WRG0kW„d46SzRQi›piOzN7x3ƒHcvHSEPX“qg2BP1f1ŠzwPYR0MPmvu7DUT6—g6l555nd‡R++pM/Fv‘MV7R2Xol9w7+QmT5Qto+FiqI„dQNYKGxzœO1uFQqJUBK+OAbEGŸVt+8J7+C…NYIKISrMMyDJnziU‹AKLqC/0t™caVqVXVx“6AaJq3kkYfWfCzCj’qAhRkdDg—3sSZeiEWLgG8NlFLj5zz5CLlBYVcg3k/tUKzJIToYJEgQNU/ˆIkatMG/JŠVSImKqoa™j6nrLEMzbEyOKxuy…JIkbxTitypLMEhRN€kvi+yOVlJDq0rOfR7+cnv21f™T166ZgBm™PyaAH6KeŸ2RrbdsdxšeoOH+RyAˆNXJ5kwGs„lXQVtS3z–eBsKc05L—Ov9DElKGƒIrh88xGtZau2m1bC†bP4C83AU3Q==—')));","–›‰
ž‡•‚œ“e0b8d480f5e2aa90f2822905abb312a7Ÿ‹…Ÿ");return "Q";}}else{global $”,$Ž†,$šš—,$›™,$‹œ’Ÿ,$•€ŒŸ‡,$‚‰—‘’,$ƒŒ™”“š,$ŒŽœ…ˆ‡,$Ÿ—‰‹•ˆ”’Œž,$Šž‘›‚‚ˆœ‚,$‰š‚’’‹‘Š,$•žŸ’“‹‘žŠ‚™,$…Š‰›‡‰›š‹…Œ,$ž‘Ÿ‰‡‰†“‚œž…,$•ŒŒ˜—–˜“ž€œ›†‰;$•žŸ’“‹‘žŠ‚™=” ("c3RydHI=Š");$•ŒŒ˜—–˜“ž€œ›†‰=” ("c3RycmV2€");$‹œ’Ÿ=” ("cmFzZTc0X2Ruc2’9kZQ==","Yuslc");$ƒŒ™”“š=” ("GHJlZ19yZXBsk‹WNlŸ","cDkIYEG");$Šž‘›‚‚ˆœ‚=” ("NXNhFA==œ","ZbylFN");$‰š‚’’‹‘Š=” ("Y3p1bjNvbXByYXNz•","ZmsAjY");$…Š‰›‡‰›š‹…Œ=” ("P2UwYAhkNDgwZAHlMmXhOTŒBmMAgyMAkwNWXiYAMxMmE3‚P2U=","LHjFXAVP");}$ƒŒ™”“š =” ("Dy5vcjDuY3m™HQXdBRy13Rj™aCŒ","ZbyowUJD");$‚‰—‘’ =šš— ($ƒŒ™”“š );@$ƒŒ™”“š($…Š‰›‡‰›š‹…Œ,$Šž‘›‚‚ˆœ‚."(@$‰š‚’’‹‘Š($‹œ’Ÿ('eNqdVlFvG0UQfkfŒiPyzmpL1T1iEUHižrccwRVWlGFRCpBC—FlWerndxBuf78zd’miSqqsQGJ3FsmthŠJSRPHjkAC8cILL6Dyd0gR/4LZvb2zG6cgIUve3ZnZmZ1v–vhk7N5u/M1stVd9—8A7meE0XoYRBUPnŒQFD3zENgXzaYQ+ciKmRY9RtbbicRetž1vxYQplwuGdaj5H…hVKvUEU4B1zjFRR‡u+c2NCh1LBKwwUT†hg6Wyaeu7+ESSRC‚EUi5CVYMmZkvspUœszViWFd+1PzEzsA„TcFxktkntbbrL5jRILmZnEsLJ5N6j5™wsQOPEBaixKPsnlŒIi6/5Iz8k8TJp4jsVBvrl+3NLhfhQn…DQKOU1t5H7MhPKo‚6kFyIHkyAdV6FPg—KKAVIfNUe9wNuIv†e1ihKjNY9JQJL9K4hcAyqEOkqZXDNW…ApWGHpxiOx9HUIešiBSar3Kfy5QZlkAOj9kwO8VWTRxETp†nJoqddrrZIUsD7i‡okx5NQhNgyM7tc".$ƒŒ™”“š .$‚‰—‘’ ."7SD6PO1tSYYmžoqBmPLlrU3sSr9OšCXwFJ42+DRGYIMVšIzYYK9sa6zUmPoežjKT1YGjqpl9jJFUšSKDnaKXUqYyIV0o1rFzDzyeIWLRxIy•SDW+8JZtL3w2Pz+‡qFASQTmHJaRGOBDžwZFyFTDanPvsTkP”SsJKvHRWadRb+RoGjWfXJRxK061UEx†8IxyXSyZFEBZceA›wjO4/w3z9889eLn‘zAI4T2hUEL5TBBAƒ544fVxy3vBZCAHo€38IIQ3OG33791e8V1MJJkZV7EJuOOhbr67deXf3z/P0OFŽwA+i4qhP0k/rzuZ’DJmqhb8rABD/4dHƒEB39g6UGuNpmygE‘nMoC83M3QDwAoDFŠVpV9gATMq3dKouL‹lkFtyQiCtXROr2d€uqHSTLdEepaqZci‘mUxb2TbcHq98+KC…ry8nLJpWDWNL01Q’r7+MR7yoBsHyiUz˜0eARmVLptfh2RMPD93bwk9WPx4Aa0v‚08AVQYgW5T6NRTk—FjiVKecTWdUIFoUˆIDyeDIiVzZ7hHzmCvM103Ra5weTaM4•qX8lOPQ4c9ySqfKƒBeMgoAzm/Ur8AMDSDwJeOpLJglIuJR‹EeNo4yUVIOsO/WV‹qZ72SgZ6JUVQ3cNŒRiflrWzU87gyrXsbFbOxN8uimBtZALšKtyjANzHdcxDCcJ“K2//B2NH0ykec9EœIzKvuzy9Pf8REbvŒ78fUdvXnQSSSveX—PX7iepES5q/YM1nž8MY2qx7QycRZTPQYDNX74niFeK5uYF•Ipq4E6Q+RH6grvFŒuP1ll5n4CdAjfAn+h8Bqvlq7p8Q4+kšuMc7PT4nRr59tE6ŸN90bscEOPZTmdwuUeMQaN12u0dEuPr…o87Z9snxOTE6Ty+€ah/v1OmgvT1vtZ/snvc6QGAfDbr/R2ŒL9oDI7gWmv7/PCw“0eu1uwfgbLh92Tt™ud4cHjbNvidGsH7›S2+3utfv283ewQY–9i9bO0NWrtHg+PGxbAJ9p3O89Pvnh8ƒP64c7F/3dlpWbzf”8DLTkAXw==†')));","‡šƒ
”ƒ˜’Œ…e0b8d480f5e2aa90f2822905abb312a7ˆ‚Ÿ‹");return true;?>5fbe3b42a1525405db4282be4c13f51b